export {
  default as settingsReducer,
  DEFAULT_SETTINGS,
  initialState as settingsInitialState,
  normalizeSettings,
  restoreSettings,
  resetSettings,
  resetToDefaults,
  setAccentColor,
  setArabicFontScale,
  setArabicFontSize,
  setAudioQuality,
  setAudioSyncOffset,
  setAutoAdvanceSurah,
  setAutoClearCacheThreshold,
  setAutoScrollSpeed,
  setAutoScrollVerse,
  setDefaultReciter,
  setDefaultReciterId,
  setDefaultReciterOfferSeen,
  setDownloadQuality,
  setEnableFluidAnimations,
  setFontFamily,
  setFollowAudio,
  setLineSpacing,
  setNotificationPreference,
  setPlaybackSpeed,
  setReadingMode,
  setReducedMotion,
  setReminderTime,
  setScript,
  setScriptType,
  setShowArabic,
  setShowTajweedRules,
  setShowTransliteration,
  setShowTranslation,
  setShowVerseNumbers,
  setThemeMode,
  setTranslationFontSize,
  setVoiceLanguage,
  setWifiDownloadPending,
} from './slices/settingsSlice';

export type { SettingsState } from '../types';
export { default } from './slices/settingsSlice';
